spring.application.name=swagger-hw
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=postgres
spring.datasource.password=kunka-163
spring.jpa.hibernate.ddl=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true